### ISSUE TITLE
looks like some serious typos in Watchy_GSR.cpp

### ISSUE THREAD

**Issue by wjgeorge** [GuruSR/Watchy_GSR#12] opened 2023-04-22 22:15 UTC
Near line 1223:
    
    D = WatchTime.Local.Wday + 1; // 2.1
    H - WatchTime.Local.Hour;   // 2.1
    BatOk = (Battery.Last == 0 || Battery.Last > Battery.LowLevel);

Guessing that should be:

    H = WatchTime.Local.Hour;

**Comment by wjgeorge** [comment] 2023-04-22 22:17
I also saw on line 1162

   if (O > "") 

which certainly does not do what you think ("" is an address pointing to a null)

**Comment by GuruSR** [comment] 2023-04-24 04:18
I fixed the H = typo, actually found that a while ago and I guess didn't re-edit the file here to fix it too, 1.4.7 has that fixed, it was caused by going back and forth between SmallRTC 2.1 and 3.0.

The (O > "") works because it's an expression, if O > empty string, ...  O.length > 0 is the same thing, not sure which is faster.

Either way, those are alright now.  Thanks for noticing those.

**Comment by GuruSR** [comment] 2023-05-29 12:25
Fixed in 1.4.7.

**Closed by GuruSR** 2023-05-29 12:25 UTC
